
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/yi235g10sp8jx939zpfli0s74154ph3v-cmake-3.26.4/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.5.6 - x86_64
...
